services:
  web: &app_base
    image: wave:latest
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  #worker:
  #  <<: *app_base
  #  ports: []

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
