services:
  web: &app_base
    image: wave:test
    command: /bin/sh -c './bin/rails db:test:prepare && ./bin/rails spec'
    build:
      context: .
      target: build
    environment:
      - RAILS_ENV=test
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://dbuser:dbpassword@postgres:5432/wave?
    depends_on:
      - postgres

  postgres:
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_INITDB_ARGS="--username=dbuser"