apiVersion: v1
kind: Pod
metadata:
  labels:
    label.pod: web
  name: web
spec:
  containers:
  - name: web
    image: docker.io/xavius/wave
    env:
    - name: RAILS_ENV
      value: development
    - name: ENABLE_BOOTSNAP
      value: "true"
    - name: REDIS_URL
      value: redis://redis:6379/0
    - name: DATABASE_URL
      value: postgresql://dbuser:dbpassword@postgres:5432/wave?
    - name: PORT
      value: "8080"
