apiVersion: v1
kind: Service
metadata:
  labels:
    label.service: web
  name: web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    label.deployment: web
