name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      CI: true
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/wave_connect_test"
      SECRET_KEY_BASE: "test"

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wave_connect_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rspec --profile 5 --format json --out tmp/rspec_results.json -f p

  brakeman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman -q --no-exit-on-error

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop

